
import { AppStreamer, StreamType, LogLevel } from '@nvidia/omniverse-webrtc-streaming-library';

// TODO: Also call this one from index???
(async () => {
  await AppStreamer.connect({
    streamSource: StreamType.DIRECT,
    logLevel: LogLevel.DEBUG,
    streamConfig: {
      server: '127.0.0.1',
      signalingPort: 49100,
      mediaServer: '127.0.0.1',
      mediaPort: 47998,
      videoElementId: 'remote-video',
      audioElementId: 'remote-audio',
    },
  });
})();



/*
Mostly Generated by ChatGPT
TODO: function docs
  Populated div:
    <div class="w-48 p-2 bg-neutral-300 border rounded text-center ">
      <h1 class="font-medium text-xl"> PRIMITIVE</h1>  
      <p>Arm: <span> left</span></p> 
      <p>Pose: <span> [0.1, 0.2, 0.2]</span></p>
    </div>
*/
function populate_timeline(primitives, timeline_id) {

  const timeline = document.getElementById(timeline_id);
  timeline.innerHTML = ""; // Clear existing

  primitives.forEach((prim, index) => {
    const card = document.createElement("div");
    card.className = "w-48 p-2 bg-neutral-300 border rounded-xl text-center flex-shrink-0";

    let content = `<h1 class="font-medium text-xl">${prim.type}</h1>`;

    // Conditionally add fields
    if (prim.arm) {
      content += `<p>Arm: <span>${prim.arm}</span></p>`;
    }

    if (prim.pose) {
      const xyz = prim.pose.slice(0, 3);
      content += `<p>Pose: <span>[${xyz.join(", ")}]</span></p>`;
    }

    card.innerHTML = content;

    timeline.appendChild(card);
  });
}


// // TESTING
// const prims = [
//   { type: "home" },
//   { type: "move_to_pose", arm: "left", pose: [-0.2, 0.2, 0.2, 0.707, 0.707, 0.0, 0.0] },
//   { type: "envelop_grasp", arm: "left" },
//   { type: "release", arm: "left" },
//   { type: "envelop_grasp", arm: "right" },
//   { type: "release", arm: "right" },
//   { type: "release", arm: "right" },
//   { type: "release", arm: "right" },
// ];

// document.addEventListener("DOMContentLoaded", () => {
//   populate_timeline(prims, 'timeline');
// });



// GLOBAL STATE
let current_plan = [];

/*
TODO
*/
function show_loading() {
  const spinner = document.getElementById("loading_spinner");
  const btn = document.getElementById("submit_task");

  spinner.classList.remove("hidden");
  btn.disabled = true;
  btn.classList.add("opacity-50", "cursor-not-allowed");
}

/*
TODO
*/
function hide_loading() {
  const spinner = document.getElementById("loading_spinner");
  const btn = document.getElementById("submit_task");

  spinner.classList.add("hidden");
  btn.disabled = false;
  btn.classList.remove("opacity-50", "cursor-not-allowed");
}

/*
TODO
Mostly generated by ChatGPT
*/
async function handle_task_submit(text_id, primitive_plan_url) {
  const textarea = document.getElementById(text_id);
  const task = textarea.value.trim();

  // TODO: Revise this
  if (!task) {
    alert("Please enter a task.");
    return;
  }

  show_loading();
  try {
    const response = await fetch(primitive_plan_url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ task }),
    });

    if (!response.ok) {
      throw new Error("API request failed");
    }

    const primitives = await response.json();

    console.log("Received Plan:", primitives);

    current_plan = primitives; // Store globally

    populate_timeline(primitives, "timeline");

  } catch (err) {
    console.error("Error calling primitive_plan API:", err);
    // TODO: Handle this prettily
    alert("Failed to generate primitive plan.");
  } finally {
    hide_loading();
  }
}

/*
TODO
*/
async function handle_plan_play(plan, execute_plan_url) {
  if (!plan || plan.length === 0) {
    alert("No plan to execute.");
    return;
  }

  try {
    const response = await fetch(execute_plan_url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(plan),
    });

    if (!response.ok) {
      throw new Error("Execution failed");
    }

    const result = await response.json();
    console.log("Execution result:", result);

  } catch (err) {
    console.error("Failed to execute plan:", err);
    // TODO: handle this cleaner
    alert(`Plan execution failed: ${err}`);
  }
}

/*
TODO
*/
async function load_latest_timeline() {
  try {
    const res = await fetch(`${root_url}/api/primitive_plan/latest`);
    const latest_primitives = await res.json();
    current_plan = latest_primitives;
    populate_timeline(latest_primitives, "timeline");
  } catch (err) {
    console.error("Failed to load latest primitives:", err);
  }

}

const root_url = "http://127.0.0.1:8000"

document.addEventListener("DOMContentLoaded", async () => {
  // Load most recent prims
  load_latest_timeline();

  const task_submit_btn = document.getElementById("submit_task");
  const play_btn = document.getElementById("play");
  
  task_submit_btn.addEventListener("click", () => {
    handle_task_submit("task_input", `${root_url}/api/primitive_plan`);
  });

  play_btn.addEventListener("click", () => {
    handle_plan_play(current_plan, `${root_url}/api/execute_plan`);
  });
});

hide_loading();