
import {ROOT_URL} from "./constants.js"
import { start_isaacsim_stream } from "./streaming.js";


// GLOBAL STATE
// TODO: REVISE
let current_plan = [];
let current_editing_primitive_idx = null;


// TODO: Also call this one from index???





/*
Mostly Generated by ChatGPT
TODO: function docs
  Populated div:
    <div class="w-48 p-2 bg-neutral-300 border rounded text-center ">
      <h1 class="font-medium text-xl"> PRIMITIVE</h1>  
      <p>Arm: <span> left</span></p> 
      <p>Pose: <span> [0.1, 0.2, 0.2]</span></p>
    </div>
*/
function populate_timeline(primitives, timeline_id) {

  const timeline = document.getElementById(timeline_id);
  timeline.innerHTML = ""; // Clear existing

  primitives.forEach((prim, index) => {
    const card = document.createElement("div");
    card.className = "w-48 p-2 bg-neutral-300 border rounded-xl text-center flex-shrink-0";

    let content = `<h1 class="font-medium text-xl">${prim.type}</h1>`;

    // Conditionally add fields
    if (prim.arm) {
      content += `<p>Arm: <span>${prim.arm}</span></p>`;
    }

    if (prim.pose) {
      const xyz = prim.pose.slice(0, 3);
      content += `<p>Pose: <span>[${xyz.join(", ")}]</span></p>`;
    }

    card.innerHTML = content;
    

    card.addEventListener("click", () => {
      open_primitive_editor(index);
    });


    timeline.appendChild(card);
  });
}


function open_primitive_editor(index) {
  const prim = current_plan[index];
  current_editing_primitive_idx = index;
  

  // Fill fields
  document.getElementById("primitive_type").innerHTML = prim.type ?? "";

  // ARM field
  if ("arm" in prim) {
    document.getElementById("arm_field").classList.remove("hidden");
    document.getElementById("edit_arm").value = prim.arm ?? "";
  } else {
    document.getElementById("arm_field").classList.add("hidden");
  }

  // POSE field
  if ("pose" in prim) {
    document.getElementById("pose_field").classList.remove("hidden");
    document.getElementById("edit_pose").value = prim.pose.join(", ");
  } else {
    document.getElementById("pose_field").classList.add("hidden");
  }

  document.getElementById("primitive_modal").classList.remove("hidden");

}

function save_primitive_edit() {
  
  const prim = current_plan[current_editing_primitive_idx];

  if ("arm" in prim) {
    const arm = document.getElementById("edit_arm").value;
    if (arm) prim.arm = arm;
  } 
  
  if ("pose" in prim) {
    const pose_str = document.getElementById("edit_pose").value;
    prim.pose = pose_str.split(",").map(Number);
  }

  current_plan[current_editing_primitive_idx] = prim;
  populate_timeline(current_plan, "timeline");
  close_primitive_editor("primitive_modal");
}


/* TODO */
function close_primitive_editor(modal_id) {
  document.getElementById(modal_id).classList.add("hidden");
  current_editing_primitive_idx = null;
}





/*
TODO
*/
function show_loading() {
  const spinner = document.getElementById("loading_spinner");
  const btn = document.getElementById("submit_task");

  spinner.classList.remove("hidden");
  btn.disabled = true;
  btn.classList.add("opacity-50", "cursor-not-allowed");
}

/*
TODO
*/
function hide_loading() {
  const spinner = document.getElementById("loading_spinner");
  const btn = document.getElementById("submit_task");

  spinner.classList.add("hidden");
  btn.disabled = false;
  btn.classList.remove("opacity-50", "cursor-not-allowed");
}

/*
TODO
Mostly generated by ChatGPT
*/
async function handle_task_submit(text_id, primitive_plan_url) {
  const textarea = document.getElementById(text_id);
  const task = textarea.value.trim();

  // TODO: Revise this
  if (!task) {
    alert("Please enter a task.");
    return;
  }

  show_loading();
  try {
    const response = await fetch(primitive_plan_url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ task }),
    });

    if (!response.ok) {
      throw new Error("API request failed");
    }

    const primitives = await response.json();

    console.log("Received Plan:", primitives);

    current_plan = primitives; // Store globally

    populate_timeline(primitives, "timeline");

  } catch (err) {
    console.error("Error calling primitive_plan API:", err);
    // TODO: Handle this prettily
    alert("Failed to generate primitive plan.");
  } finally {
    hide_loading();
  }
}

/*
TODO
*/
async function handle_plan_play(plan, execute_plan_url) {
  if (!plan || plan.length === 0) {
    alert("No plan to execute.");
    return;
  }

  try {
    const response = await fetch(execute_plan_url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(plan),
    });

    if (!response.ok) {
      throw new Error("Execution failed");
    }

    const result = await response.json();
    console.log("Execution result:", result);

  } catch (err) {
    console.error("Failed to execute plan:", err);
    // TODO: handle this cleaner
    alert(`Plan execution failed: ${err}`);
  }
}

/*
TODO
*/
async function load_latest_timeline() {
  try {
    const res = await fetch(`${ROOT_URL}/api/primitive_plan/latest`);
    const latest_primitives = await res.json();
    current_plan = latest_primitives;
    populate_timeline(latest_primitives, "timeline");
  } catch (err) {
    console.error("Failed to load latest primitives:", err);
  }

}

/*
TODO
*/
async function load_objects() {
  try {
    await fetch(`${ROOT_URL}/api/spawn_objects`, {
      method: "POST"});

  } catch (err) {
    console.error("Failed to spawn objects: ", err);
  }

}




document.addEventListener("DOMContentLoaded", async () => {
  await start_isaacsim_stream();

  load_objects();
  // Load most recent prims
  load_latest_timeline();

  const task_submit_btn = document.getElementById("submit_task");
  const play_btn = document.getElementById("play");
  const execute_on_robot_btn = document.getElementById("execute_on_robot");
  
  task_submit_btn.addEventListener("click", () => {
    handle_task_submit("task_input", `${ROOT_URL}/api/primitive_plan`);
  });

  play_btn.addEventListener("click", () => {
    handle_plan_play(current_plan, `${ROOT_URL}/api/execute_plan?on_real=false`);
  });

  execute_on_robot_btn.addEventListener("click", () => {
    handle_plan_play(current_plan, `${ROOT_URL}/api/execute_plan?on_real=true`);
  });

  // Primitive Edit Modal
  document.getElementById("cancel_edit").addEventListener("click", () => {
    close_primitive_editor("primitive_modal", );
  });

  // Primitive Edit Modal
  document.getElementById("save_edit").addEventListener("click", () => {
    save_primitive_edit();
  });

});
