import {set_state} from "/src/js/state.js";
import { post_task } from "/src/js/helpers/api";

/*
TODO
*/
function show_loading() {
  const spinner = document.getElementById("loading_spinner");
  const btn = document.getElementById("submit_task");

  spinner.classList.remove("hidden");
  btn.disabled = true;
  btn.classList.add("opacity-50", "cursor-not-allowed");
}

/*
TODO
*/
function hide_loading() {
  const spinner = document.getElementById("loading_spinner");
  const btn = document.getElementById("submit_task");

  spinner.classList.add("hidden");
  btn.disabled = false;
  btn.classList.remove("opacity-50", "cursor-not-allowed");
}

/*
TODO
Mostly generated by ChatGPT
*/
export async function handle_task_submit(text_id) {
    const textarea = document.getElementById(text_id);
    const task = textarea.value.trim();

    // TODO: Revise this
    if (!task) {
        alert("Please enter a task.");
        return;
    }

  show_loading();
    try {
        const primitives = await post_task(task);
        console.log("Received Plan:", primitives);
        set_state({plan: primitives});

    } catch (err) {
        console.error("Error calling primitive_plan API:", err);
        // TODO: Handle this prettily
        alert("Failed to generate primitive plan.");
    } finally {
        hide_loading();
    }
}